# test:
#   post:
#     - bundle exec slather
#     - bash <(curl -s https://codecov.io/bash) -f fastlane/reports/coverage/slather/cobertura.xml -X coveragepy -X gcov -X xcode
# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2

jobs:
    # Specify the Xcode version to use
    macos:
        xcode: "9.2.0"
    environment:
      CIRCLE_TEST_REPORTS: ~/test-reports
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    build_and_test:
      steps:
        - checkout

        # Restore bundle cache
        - restore_cache:
          key: v1-macos-gems-{{ checksum "Gemfile" }}-{{ checksum "fastlane.gemspec" }}
        - restore_cache:
            keys:
              - v3-homebrew-{{ epoch }}
              - v3-homebrew
        - run:
            name: Install Homebrew and Ruby Dependencies
            command: |
              brew install rbenv ruby-build shellcheck
              ruby-build 2.4.1
        - run:
            name: Bundle install
            command: |
              mkdir -p ~/test-reports
              gem update --system
              bundle check --path .bundle || bundle install --jobs=4 --retry=3 --path .bundle
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
            # This is the path where all the gems will be installed, and
            # which CircleCI will later cache.
            BUNDLE_PATH: .bundle

        # Build the app and run tests
        - run:
            name: Build and run tests
            command: bundle exec fastlane ios test

        # Collect XML test results data to show in the UI,
        # and save the same XML files under test-results folder
        # in the Artifacts tab
        - store_test_results:
            path: fastlane/reports/coverage/slather/report.xml
        - store_artifacts:
            path: fastlane/reports/test-results
            destination: scan-test-results
        - store_artifacts:
            path: ~/Library/Logs/scan
            destination: scan-logs
        # Store bundle cache
        - save_cache:
          key: v3-homebrew-{{ epoch }}
          paths:
            - /usr/local/Homebrew
        - save_cache:
            key: v1-macos-gems-{{ checksum "Gemfile" }}-{{ checksum "fastlane.gemspec" }}
            paths:
              - .bundle