# test:
#   post:
#     - bundle exec slather
#     - bash <(curl -s https://codecov.io/bash) -f fastlane/reports/coverage/slather/cobertura.xml -X coveragepy -X gcov -X xcode
# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.2"

    steps:
      - checkout

      - run:
        name: Bundle install
        command: bundle check || bundle install
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          # This is the path where all the gems will be installed, and
          # which CircleCI will later cache.
          BUNDLE_PATH: vendor/bundle

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: bundle exec fastlane ios test

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: fastlane/reports/coverage/slather/report.xml
      - store_artifacts:
          path: fastlane/reports/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
