# test:
#   post:
#     - bundle exec slather
#     - bash <(curl -s https://codecov.io/bash) -f fastlane/reports/coverage/slather/cobertura.xml -X coveragepy -X gcov -X xcode
# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2

jobs:
  build-and-test:
    macos:
      xcode: "9.4.1"
    shell: /bin/bash --login -eo pipefail
    environment:
      CIRCLE_TEST_REPORTS: ~/test-reports
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
      - checkout
      - restore_cache:
          key: v1-macos-gems-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          keys:
            - v3-homebrew-{{ epoch }}
      - run:
          name: Bundle install
          command: |
            echo "rubies $(chruby)"
            mkdir -p ~/test-reports
            gem update --system
            bundle check --path .bundle || bundle install --jobs=4 --retry=3 --path .bundle
            echo "Done!"
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3
            # This is the path where all the gems will be installed, and
            # which CircleCI will later cache.
            BUNDLE_PATH: .bundle

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: bundle exec fastlane ios test

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: fastlane/reports/coverage/slather/cobertura.xml
      - store_artifacts:
          path: fastlane/reports/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
      # Store bundle cache
      - save_cache:
          key: v3-homebrew-{{ epoch }}
          paths:
            - /usr/local/Homebrew
      - save_cache:
          key: v1-macos-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - .bundle
workflows:
  version: 2
  buildtest:
    jobs:
    - build-and-test
