
default_platform(:ios)

platform :ios do

  before_all do
    cocoapods(
        clean: true,
        repo_update: false,
        use_bundle_exec: true
      )
  end

  desc "Runs tests and generates coverage report"
  lane :test do |options|

    lint_pod
    compile_and_test(scheme: options[:scheme])
    danger_run
    generate_test_coverage
  end

  # Private lanes

  desc "Run tests"
  private_lane :compile_and_test do |options|
    scan(scheme: options[:scheme])
  end

  desc "Cocoapods pod lib lint"
  private_lane :lint_pod do
    pod_lib_lint(
      allow_warnings: true
    )
end

  desc "Calculate code coverage"
  private_lane :generate_test_coverage do
    slather(html: true, cobertura_xml: true, use_bundle_exec: true)
    codecov(path: "fastlane/reports/coverage/slather/cobertura.xml")
    #sh "curl -s https://codecov.io/bash -f fastlane/reports/coverage/slather/cobertura.xml -X coveragepy -X gcov -X xcode"
  end

  desc "Run Danger"
  private_lane :danger_run do
    danger(
      danger_id: "unit-tests",
      dangerfile: "DangerFile",
      github_api_token: ENV["GITHUB_API_TOKEN"],
      verbose: true
    )
  end
end
