
default_platform(:ios)

platform :ios do

  before_all do
    cocoapods(
        clean: true,
        repo_update: true,
        use_bundle_exec: true
      )
  end

  desc "Runs tests and generates coverage report"
  lane :test do |options|

    compile_and_test(scheme: options[:scheme])
    generate_test_coverage
  end

  # Private lanes

  desc "Run tests"
  private_lane :compile_and_test do |options|

    scan(scheme: options[:scheme])
  end

  desc "Calculate code coverage"
  private_lane :generate_test_coverage do

    slather(html: true)
  end
end
